### ISSUE TITLE
Please add inverted

### ISSUE THREAD

**Issue by xcxooxl** [bolan9999/react-native-spring-scrollview#17]
I'm actually using largeListV3 and I thought I finally found a good list for my chat, But this list doesn't have inverted prop.

**Comment by bolan9999** [comment]
Use `transform` props to flip both `LargeList` and `renderIndexPath` . All will be ok!

**Comment by bolan9999** [comment]
I am adding some lottie animation guide to the docs. Busy,now

**Comment by bolan9999** [comment]
Add `{transform:[{rotate:"180deg"}]}` to your `LargeList`, `renderHeader`,`renderSection`,`renderIndexPath`, `renderFooter` style. And hide indicator.

**Comment by xcxooxl** [comment]
I did but scrolling behaved really off.
It tried to scroll in the direction of my finger then goes back.

**Comment by bolan9999** [comment]
I have tried it with my example. And it all works well. The only problem is indicator is not correct.

**Comment by bolan9999** [comment]
I do not understand your issue.

**Comment by bolan9999** [comment]
Could you please make a video?

**Comment by xcxooxl** [comment]
https://we.tl/t-elhZOy1iMu

As you can see after rotating it, The scroll direction behaves weird.
This doesn't happen if I don't rotate the views.

**Comment by xcxooxl** [comment]
password is 123456

**Comment by bolan9999** [comment]
How do you update your source? do you call scrollTo?

**Comment by xcxooxl** [comment]
I used to but I think I commented it out (not near computer ATM) ,Still there's no reason for the source to update,  I'm not adding or modifying, etc in the example, Also this behavior only happens after rotate.

**Comment by bolan9999** [comment]
I got it. I am going to fix it.

**Comment by bolan9999** [comment]
I have published V3.0.4. Inverted is full supported. Please update to :
```
react-native-largelist-v3  v3.0.4
react-native-spring-scrollview v2.0.8
```

A [chat example](https://github.com/bolan9999/react-native-largelist/blob/master/Examples/ChatExample.js) is in the latest version. You can clone `react-native-largelist` repo on the github to try it.

**Comment by bolan9999** [comment]
sorry，3.0.4 has a little problem. please update 3.0.5.

**Comment by xcxooxl** [comment]
Sorry man, still not working, I removed the 180deg rotations and added inverted like the example
after adding inverted the scroll behaves as you can see in this video,

Also inverted list should start from bottom to top and I'm still experiencing that the list is being rendered from top to bottom ( I guess I can fix that by sorting the data, I don't think it's as important as the scroll issue.)

video: 
https://drive.google.com/open?id=1Gq_S_6eimEsj2Hq-FEOyM1aSd-ID85ue

**Comment by bolan9999** [comment]
Please confirm your version is correct. And clear all cache! If you got some issue on my ChatExample, then send me an issue, please.

**Comment by bolan9999** [comment]
Or you can create a new repo with the latest version(v3.0.5 / 2.0.8) . Sometimes, the cache is terrible to clear.

**Comment by bolan9999** [comment]
I feel I got your problem now. The android emulator and real device has different behaviors between them. If you try on emulator, It works well. I need more test.

**Comment by bolan9999** [comment]
I'm not sure whether the problem is the system version. I do not have enough devices to test.

**Comment by xcxooxl** [comment]
That's too bad, You think you can finish it soon? ,Our team wanted to use this library in production (We are building a chat app customized to our needs)

If you can, Give me your time estimate so I will know what's my best move.

**Comment by bolan9999** [comment]
You can fix by yourself:
comment these code in SpringScrollView.java on real devices and keep them on the android emulator.Or you can add emulator checking. 
```
//        if (inverted) {
//            vx = -vx;
//            vy = -vy;
//        }
```

**Comment by bolan9999** [comment]
I tried to add an emulator checking on SpringScrollView 2.0.9, update it.

**Comment by xcxooxl** [comment]
Scrolling still going backwards but it feels somewhat less aggressive than before.

**Comment by bolan9999** [comment]
Clone `https://github.com/bolan9999/react-native-largelist` and try my example. Compare and show more information. Or show me your code and your environment information. There is not problem on my chatExample. Your information is too less. The problem will never be resolved like this talking. 

```
    1. Dev OS (windows/Mac/Linux)
    2. Target OS (iOS/Android/Both)
    3. Simulator or real device? (Simulator/Real Device/Both)
    4. The version of react-native, react-native-spring-scrollview, react-native-largelist
    5. Your code
    6. Picture or videos of issue if required!
```

**Comment by bolan9999** [comment]
And it is a waste of time.

**Comment by bolan9999** [comment]
I guess you use the old version with cache or you do not recompile your project!

**Comment by bolan9999** [comment]
Or you make a repo and let me debug it!
